title: Code.github.io
description: Help you code a discord bot!
theme: jekyll-theme-midnight
show_downloads: true
toggle-sidebar-button: true
sidebars:
  interaction
link_type: jurl
github:
  zip_url: https://t2k-official.github.io/t2manager.github.io
  repository_url: https://discord.gg/aMgCkekQJ9
  tar_url: https://top.gg/bot/982953875915034644
